#!/usr/bin/env python3
"""
NIDS Dashboard - Fixed with Report Download
Handles all data types properly for JSON serialization
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
import sys
import os
import json
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(
    page_title="🛡️ NIDS - Complete Dashboard",
    page_icon="🛡️",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
    .stApp { background: linear-gradient(135deg, #0a0e27 0%, #1a1f3a 100%); }
    .metric-card {
        background: rgba(255,255,255,0.05);
        border-radius: 12px;
        padding: 20px;
        text-align: center;
        border: 1px solid rgba(255,255,255,0.1);
        transition: all 0.3s ease;
    }
    .metric-card:hover {
        transform: scale(1.02);
        border-color: #00d4ff;
    }
</style>
""", unsafe_allow_html=True)

# ============= HELPER FUNCTIONS =============

def convert_to_serializable(obj):
    """Convert numpy types to Python types for JSON serialization"""
    if isinstance(obj, (np.int64, np.int32, np.int16, np.int8)):
        return int(obj)
    elif isinstance(obj, (np.float64, np.float32, np.float16)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, pd.Series):
        return obj.to_dict()
    elif isinstance(obj, dict):
        return {key: convert_to_serializable(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_to_serializable(item) for item in obj]
    else:
        return obj

# ============= REPORT GENERATION FUNCTIONS =============

def generate_markdown_report(df, label_counts, total, ddos_count, benign_count):
    """Generate and download Markdown report"""
    
    report = f"""# Network Intrusion Detection Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Total Samples:** {total:,}
**Features:** {len(df.columns)}

---

## 1. Dataset Summary

| Metric | Value |
|--------|-------|
| Total Samples | {total:,} |
| DDoS Attacks | {ddos_count:,} ({ddos_count/total*100:.1f}%) |
| BENIGN Traffic | {benign_count:,} ({benign_count/total*100:.1f}%) |
| Attack Ratio | {ddos_count/benign_count:.2f}x |

---

## 2. Class Distribution

| Class | Count | Percentage |
|-------|-------|------------|
"""
    
    for label, count in label_counts.items():
        report += f"| {label} | {count:,} | {count/total*100:.1f}% |\n"
    
    report += f"""
---

## 3. Feature Information

**Total Features:** {len(df.columns)}
**Numeric Features:** {len(df.select_dtypes(include=[np.number]).columns)}
**Categorical Features:** {len(df.select_dtypes(include=['object']).columns)}

### Column List
"""
    
    for col in df.columns:
        report += f"- {col}\n"
    
    report += f"""
---

## 4. Statistical Summary

### Numeric Features
"""
    
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols[:10]:
        report += f"- **{col}**: Mean = {df[col].mean():.4f}, Std = {df[col].std():.4f}\n"
    
    report += f"""
---

## 5. Recommendations

{'⚠️ **HIGH ATTACK RATE DETECTED!** Immediate action recommended.' if ddos_count/total > 0.5 else '✅ Low attack rate. Continue monitoring.'}

### Actions:
1. {'Block malicious IP addresses' if ddos_count > 0 else 'Monitor for normal traffic'}
2. {'Enable rate limiting' if ddos_count/total > 0.3 else 'Maintain current security posture'}
3. {'Investigate attack patterns' if ddos_count > 100 else 'No immediate action required'}

---

**Report Generated by:** AI NIDS System
**Version:** 2.0
"""
    
    st.download_button(
        label="📥 Download Markdown Report",
        data=report,
        file_name=f"nids_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
        mime="text/markdown",
        key="md_download"
    )
    st.success("✅ Markdown report generated!")

def generate_json_report(df, label_counts, total, ddos_count, benign_count):
    """Generate and download JSON report"""
    
    # Convert all numpy types to Python types
    label_counts_serializable = convert_to_serializable(label_counts)
    
    report = {
        'report_info': {
            'generated': datetime.now().isoformat(),
            'version': '2.0'
        },
        'dataset_summary': {
            'total_samples': int(total),
            'features': int(len(df.columns)),
            'ddos_count': int(ddos_count),
            'ddos_percentage': float(ddos_count/total*100),
            'benign_count': int(benign_count),
            'benign_percentage': float(benign_count/total*100),
            'attack_ratio': float(ddos_count/benign_count) if benign_count > 0 else 0
        },
        'class_distribution': label_counts_serializable,
        'feature_info': {
            'numeric_features': int(len(df.select_dtypes(include=[np.number]).columns)),
            'categorical_features': int(len(df.select_dtypes(include=['object']).columns)),
            'column_names': df.columns.tolist()
        },
        'statistics': {
            'numeric_columns': df.select_dtypes(include=[np.number]).columns.tolist()[:10]
        },
        'recommendations': {
            'risk_level': 'HIGH' if ddos_count/total > 0.5 else 'LOW',
            'actions': [
                'Block malicious IP addresses' if ddos_count > 0 else 'Monitor for normal traffic',
                'Enable rate limiting' if ddos_count/total > 0.3 else 'Maintain current security posture'
            ]
        }
    }
    
    report_json = json.dumps(report, indent=2)
    
    st.download_button(
        label="📥 Download JSON Report",
        data=report_json,
        file_name=f"nids_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
        mime="application/json",
        key="json_download"
    )
    st.success("✅ JSON report generated!")

def generate_csv_report(df):
    """Generate and download CSV report"""
    
    report_df = df.copy()
    report_df['analysis_date'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    if 'Label' in report_df.columns:
        report_df['risk_level'] = report_df['Label'].apply(
            lambda x: 'HIGH' if x != 'BENIGN' else 'LOW'
        )
    
    csv = report_df.to_csv(index=False)
    
    st.download_button(
        label="📥 Download CSV Report",
        data=csv,
        file_name=f"nids_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
        mime="text/csv",
        key="csv_download"
    )
    st.success("✅ CSV report generated!")

def generate_txt_report(df, label_counts, total, ddos_count, benign_count):
    """Generate and download TXT report"""
    
    report = f"""
====================================
NETWORK INTRUSION DETECTION REPORT
====================================

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Total Samples: {total:,}
Features: {len(df.columns)}

------------------------------------
DATASET SUMMARY
------------------------------------
DDoS Attacks: {ddos_count:,} ({ddos_count/total*100:.1f}%)
BENIGN Traffic: {benign_count:,} ({benign_count/total*100:.1f}%)
Attack Ratio: {ddos_count/benign_count:.2f}x

------------------------------------
CLASS DISTRIBUTION
------------------------------------
"""
    
    for label, count in label_counts.items():
        report += f"{label}: {count:,} ({count/total*100:.1f}%)\n"
    
    report += f"""
------------------------------------
FEATURES
------------------------------------
Total Features: {len(df.columns)}
Numeric Features: {len(df.select_dtypes(include=[np.number]).columns)}
Categorical Features: {len(df.select_dtypes(include=['object']).columns)}

------------------------------------
RECOMMENDATIONS
------------------------------------
{'⚠️ HIGH ATTACK RATE - Immediate action required!' if ddos_count/total > 0.5 else '✅ Low attack rate - Continue monitoring'}

Actions:
1. {'Block malicious IP addresses' if ddos_count > 0 else 'Monitor for normal traffic'}
2. {'Enable rate limiting' if ddos_count/total > 0.3 else 'Maintain current security posture'}

------------------------------------
Report Generated by: AI NIDS System
Version: 2.0
"""
    
    st.download_button(
        label="📥 Download TXT Report",
        data=report,
        file_name=f"nids_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
        mime="text/plain",
        key="txt_download"
    )
    st.success("✅ TXT report generated!")

# ============= MAIN DASHBOARD =============

st.title("🛡️ Network Intrusion Detection System")
st.markdown("### Complete Dashboard with Report Generation")

# Sidebar
with st.sidebar:
    st.markdown("### 📤 Upload Dataset")
    
    uploaded_file = st.file_uploader("Choose CSV file", type=['csv'])
    
    if uploaded_file is not None:
        try:
            df = pd.read_csv(uploaded_file)
            df.columns = df.columns.str.strip()
            
            st.session_state.df = df
            st.success(f"✅ Loaded {len(df):,} rows")
            
            st.markdown("---")
            st.markdown("### 📊 Dataset Info")
            st.write(f"**Rows:** {len(df):,}")
            st.write(f"**Columns:** {len(df.columns)}")
            
            if 'Label' in df.columns:
                counts = df['Label'].value_counts()
                st.write("**Class Distribution:**")
                for label, count in counts.items():
                    st.write(f"  • {label}: {count:,} ({count/len(df)*100:.1f}%)")
            
        except Exception as e:
            st.error(f"Error: {e}")

# Main content
if 'df' in st.session_state:
    df = st.session_state.df
    
    if 'Label' in df.columns:
        # Get actual counts
        label_counts = df['Label'].value_counts()
        total = len(df)
        
        ddos_count = label_counts.get('DDoS', 0)
        benign_count = label_counts.get('BENIGN', 0)
        
        # Display metrics
        st.markdown("### 📊 Dataset Statistics")
        
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            st.markdown(f"""
            <div class="metric-card">
                <div style="color: rgba(255,255,255,0.6);">Total Samples</div>
                <div style="font-size: 2rem; font-weight: 700; color: #00d4ff;">{total:,}</div>
            </div>
            """, unsafe_allow_html=True)
        
        with col2:
            st.markdown(f"""
            <div class="metric-card">
                <div style="color: rgba(255,255,255,0.6);">🚨 DDoS Attacks</div>
                <div style="font-size: 2rem; font-weight: 700; color: #ff0066;">{ddos_count:,}</div>
                <div style="color: rgba(255,255,255,0.4);">{ddos_count/total*100:.1f}%</div>
            </div>
            """, unsafe_allow_html=True)
        
        with col3:
            st.markdown(f"""
            <div class="metric-card">
                <div style="color: rgba(255,255,255,0.6);">✅ BENIGN Traffic</div>
                <div style="font-size: 2rem; font-weight: 700; color: #00ff88;">{benign_count:,}</div>
                <div style="color: rgba(255,255,255,0.4);">{benign_count/total*100:.1f}%</div>
            </div>
            """, unsafe_allow_html=True)
        
        with col4:
            st.markdown(f"""
            <div class="metric-card">
                <div style="color: rgba(255,255,255,0.6);">Attack Ratio</div>
                <div style="font-size: 2rem; font-weight: 700; color: #ffaa00;">{ddos_count/benign_count:.2f}x</div>
                <div style="color: rgba(255,255,255,0.4);">DDoS : BENIGN</div>
            </div>
            """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        # Visualization
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("#### 🎯 Class Distribution")
            
            fig = go.Figure(data=[go.Pie(
                labels=label_counts.index,
                values=label_counts.values,
                marker=dict(colors=['#00ff88' if l == 'BENIGN' else '#ff0066' for l in label_counts.index]),
                textinfo='label+percent+value',
                hovertemplate="<b>%{label}</b><br>Count: %{value:,}<br>Percentage: %{percent}"
            )])
            
            fig.update_layout(
                height=400,
                paper_bgcolor='rgba(0,0,0,0)',
                font={'color': 'white'}
            )
            
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            st.markdown("#### 📊 Distribution Bar Chart")
            
            fig = go.Figure(data=[go.Bar(
                x=label_counts.index,
                y=label_counts.values,
                marker_color=['#00ff88' if l == 'BENIGN' else '#ff0066' for l in label_counts.index],
                text=label_counts.values,
                textposition='auto'
            )])
            
            fig.update_layout(
                height=400,
                xaxis_title="Class",
                yaxis_title="Count",
                paper_bgcolor='rgba(0,0,0,0)',
                plot_bgcolor='rgba(0,0,0,0)',
                font={'color': 'white'}
            )
            
            st.plotly_chart(fig, use_container_width=True)
        
        st.markdown("---")
        
        # Report Generation Section
        st.markdown("### 📋 Generate Report")
        
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            if st.button("📄 Markdown Report", use_container_width=True):
                generate_markdown_report(df, label_counts, total, ddos_count, benign_count)
        
        with col2:
            if st.button("📊 JSON Report", use_container_width=True):
                generate_json_report(df, label_counts, total, ddos_count, benign_count)
        
        with col3:
            if st.button("📥 CSV Report", use_container_width=True):
                generate_csv_report(df)
        
        with col4:
            if st.button("📝 TXT Report", use_container_width=True):
                generate_txt_report(df, label_counts, total, ddos_count, benign_count)
        
        st.markdown("---")
        
        # Data preview
        st.markdown("### 📄 Data Preview")
        st.dataframe(df.head(100), use_container_width=True)
        
        # Summary statistics
        st.markdown("### 📈 Summary Statistics")
        
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            stats = df[numeric_cols].describe()
            st.dataframe(stats, use_container_width=True)

else:
    st.info("📤 Please upload a dataset in the sidebar")

# Footer
st.markdown("---")
st.caption("🛡️ NIDS Dashboard | Complete Report Generation | v2.0")
